version: 2.1

orbs:
  win: circleci/windows@2.0.0

jobs:
  build_linux:
    docker:
      - image: circleci/python:3.7.4

    working_directory: ~/relocation-app

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo pip install -r dev_requirements.txt
      - run:
          name: setup movable virtualenv
          command: |
            virtualenv --no-site-packages --always-copy movable
            . movable/bin/activate
            pip install -r requirements.txt
      - run:
          name: package movable virtualenv
          command: |
            venv-pack -p movable
      - run:
          name: test move virtual environment
          command: |
            rm -rf movable
            mkdir moved
            tar -xzf movable.tar.gz -C moved
            . moved/bin/activate
            python versions.py

  build_windows:
    executor: win/default
    steps:
      - checkout
      - run:
          name: install python
          command: choco install python --version 3.7.4
      - run:
          name: install dependencies
          command: |
            pip install -r dev_requirements.txt
      - run:
          name: patch venv-pack for windows support
          command: |
            md C:\Python37\lib\site-packages\venv_pack\scripts\nt
            copy activate.bat C:\Python37\lib\site-packages\venv_pack\scripts\nt
      - run:
          name: setup movable virtualenv
          command: |
            virtualenv --no-site-packages --always-copy movable
            movable\Scripts\activate.bat
            pip install -r requirements.txt
      - run:
          name: package movable virtualenv
          command: |
            venv-pack --format zip -p movable
      - run:
          name: test move virtual environment
          command: |
            Remove-Item –path movable –recurse
            md moved
            Expand-Archive movable.zip -DestinationPath moved
            moved\Scripts\activate.bat
            python versions.py

workflows:
  version: 2
  build_all:
    jobs:
      - build_linux
      - build_windows