version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build_linux:
    docker:
      - image: circleci/python:3.7.4

    working_directory: ~/relocation-app

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r dev_requirements.txt
            virtualenv --no-site-packages --always-copy movable
            . movable/bin/activate
            pip install -r requirements.txt
      - run:
          name: package movable virtualenv
          command: |
            . venv/bin/activate
            venv-pack -p movable
      - run:
          name: test move virtual environment
          command: |
            mkdir moved
            tar -xzf movable.tar.gz -C moved
            . moved/bin/activate
            python versions.py

  build_windows:
    executor: win/vs2019
    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'

workflows:
  version: 2
  build_all:
    jobs:
      - build_linux
      - build_windows